version: "3"

services:
    listener:
        restart: always
        build: 
          context: ./
          dockerfile: ./Dockerfile-dev
        volumes:
          - "./src:/src" 
          - "./scripts:/scripts" 
        networks:
          vpcbr:
            ipv4_address: 10.5.0.6
        environment:
          GDP_CONFIG: "docker_listener.toml"
        command: >
          bash -c "source /opt/ros/humble/setup.bash; 
          export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ;
          export CYCLONEDDS_URI=file:///fog_ws/cyclonedds.ubuntu.2204.xml ;
          ros2 run demo_nodes_py listener & 
          /gdp-router router"
    talker:
        restart: always
        build: 
          context: ./
          dockerfile: ./Dockerfile-dev
        volumes:
          - "./src:/src" 
          - "./scripts:/scripts" 
        networks:
          vpcbr:
            ipv4_address: 10.5.0.5
        environment:
          GDP_CONFIG: "docker_talker.toml"
        # depending on listener is not requierd but it makes sure that 
        # the listener is up and running before the talker starts
        depends_on:
          - listener
        command: >
          bash -c "source /opt/ros/humble/setup.bash; 
          export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp; 
          export CYCLONEDDS_URI=file:///fog_ws/cyclonedds.ubuntu.2204.xml ;
          ros2 run demo_nodes_py talker & 
          /gdp-router router"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1