version: "3"

services:
    listener:
        restart: always
        build: 
          context: ./
          dockerfile: ./Dockerfile-dev
        volumes:
          - "./src:/src" 
          - "./scripts:/scripts" 
        networks:
          vpcbr:
            ipv4_address: 10.5.0.6
        environment:
          SGC_CONFIG: "automatic.toml"
          RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
          CYCLONEDDS_URI: "file:///fog_ws/cyclonedds.ubuntu.2204.xml"
        command: >
          bash -c "source /opt/ros/humble/setup.bash; 
          ros2 run demo_nodes_py listener & 
          /gdp-router router"
    talker:
        restart: always
        build: 
          context: ./
          dockerfile: ./Dockerfile-dev
        volumes:
          - "./src:/src" 
          - "./scripts:/scripts" 
        networks:
          vpcbr:
            ipv4_address: 10.5.0.5
        environment:
          SGC_CONFIG: "automatic.toml"
          # this connects the talker to the listener
          GATEWAY_IP: "10.5.0.6"
          RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
          CYCLONEDDS_URI: "file:///fog_ws/cyclonedds.ubuntu.2204.xml"
        depends_on:
          - listener
        command: >
          bash -c "source /opt/ros/humble/setup.bash; 
          ros2 run demo_nodes_py talker & 
          /gdp-router router"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1